### ISSUE TITLE
less files do not get recompiled on file change

### ISSUE THREAD

**Issue by andyparsons** [magnars/optimus-less#4]
I'm not sure if this is intended behavior, but in dev mode, our LESS files a transpiled after a server restart, but thereafter changes in LESS files do not appear to be served until the next restart.

**Comment by magnars** [comment]
Ok, I've got a theory. You're using imports. The main file is unchanged. The modification time probably only takes into account the main file. And so, even if the changes are reflected in the file, we get a 304 Not Modifies, and the client doesn't see the changes. 

Could you test this theory by touching the main file and see that the changes then show up?

This would then not be an issue with optimus-less, but the imports inlining in optimus core.

**Comment by andyparsons** [comment]
Your theory is correct. Any workaround or optimization/strategy to apply? It makes life for our frontend folks quite difficult.

**Comment by magnars** [comment]
The quickest workaround I can think of, is to set up something like [watchr](https://rubygems.org/gems/watchr) to touch the main .less file on changes to .less-files.

For a fix, I'll have to dig into the code a bit and see how difficult that would be.

**Comment by magnars** [comment]
Fixing this seems quite doable to me. I'll take a look this evening.

**Comment by magnars** [comment]
I've released 0.17.1 of optimus with a fix for this, and also bumped optimus-less to 0.2.1 with this optimus dependency + a newer version of less4j.

**Comment by andyparsons** [comment]
Thanks @magnars! This is still not working for our case, however. Currently even touching the less file with the includes does not cause recompilation, only a server restart does.
 Our less file is simply:
```
@import "../variables";
@import "base";
@import "sidebar";
@import "color-scheme";
```
And the desire is to modify styleguide.css in the dev environment. Let me know if any other data or testing could be helpful.

**Comment by magnars** [comment]
Damn, then I'm out of ideas at the moment. Any way you could give me a minimal reconstruction of the problem?

**Comment by andyparsons** [comment]
Will try to pull something together. In the meantime, is there a strategy or optimization that would force recompilation every time? That would be a fine workaround for now.

**Comment by magnars** [comment]
From what I can understand, it does force recompilation every time - it's
just being served as unchanged by ring. You can try to remove the
wrap-not-modified middleware from your stack.

**Comment by favila** [comment]
I ran into this issue too. I believe the problem is that :references for the less only includes references from the *compiled* less file, whereas it should really only have references from the *uncompiled* file. This has to be fixed on the optimus-less side, not the optimus side. (I.e. you can't delegate all the reference-finding work to create-css-asset, because by that time it is pure css with no *.less references.)

Even further, :last-modified for css and less files should really be calculated by the last-modified not of all references, but only of `@import`ed references.
